// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/Registration.proto

package RegistrationService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegistrationRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	City                 string   `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationRequest) Reset()         { *m = RegistrationRequest{} }
func (m *RegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*RegistrationRequest) ProtoMessage()    {}
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a4df7e158e2fe3e, []int{0}
}

func (m *RegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationRequest.Unmarshal(m, b)
}
func (m *RegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationRequest.Marshal(b, m, deterministic)
}
func (m *RegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationRequest.Merge(m, src)
}
func (m *RegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_RegistrationRequest.Size(m)
}
func (m *RegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationRequest proto.InternalMessageInfo

func (m *RegistrationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegistrationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegistrationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegistrationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegistrationRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegistrationRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

type RegistrationResponse struct {
	Message              string               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 uint64               `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	RegistrationRequest  *RegistrationRequest `protobuf:"bytes,3,opt,name=registrationRequest,proto3" json:"registrationRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RegistrationResponse) Reset()         { *m = RegistrationResponse{} }
func (m *RegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*RegistrationResponse) ProtoMessage()    {}
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a4df7e158e2fe3e, []int{1}
}

func (m *RegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationResponse.Unmarshal(m, b)
}
func (m *RegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationResponse.Marshal(b, m, deterministic)
}
func (m *RegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationResponse.Merge(m, src)
}
func (m *RegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_RegistrationResponse.Size(m)
}
func (m *RegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationResponse proto.InternalMessageInfo

func (m *RegistrationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegistrationResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegistrationResponse) GetRegistrationRequest() *RegistrationRequest {
	if m != nil {
		return m.RegistrationRequest
	}
	return nil
}

func init() {
	proto.RegisterType((*RegistrationRequest)(nil), "RegistrationService.RegistrationRequest")
	proto.RegisterType((*RegistrationResponse)(nil), "RegistrationService.RegistrationResponse")
}

func init() { proto.RegisterFile("proto/Registration.proto", fileDescriptor_1a4df7e158e2fe3e) }

var fileDescriptor_1a4df7e158e2fe3e = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xb1, 0x4e, 0xc3, 0x40,
	0x10, 0x44, 0x65, 0xe3, 0x18, 0x58, 0x10, 0xc5, 0x26, 0x42, 0xab, 0x54, 0x28, 0x55, 0x68, 0x8c,
	0x14, 0xfe, 0xe4, 0xe8, 0xe8, 0x2e, 0xf6, 0x2a, 0x5a, 0x29, 0xf6, 0x99, 0xdb, 0x03, 0x04, 0x3f,
	0x42, 0xcb, 0xa7, 0xa2, 0xac, 0x03, 0x4a, 0x84, 0x8b, 0x74, 0x33, 0xcf, 0xd6, 0xdc, 0xdc, 0x1c,
	0x50, 0x1f, 0x43, 0x0a, 0x0f, 0x8e, 0x37, 0xa2, 0x29, 0xfa, 0x24, 0xa1, 0xab, 0x0c, 0xe1, 0xf4,
	0x90, 0x3d, 0x71, 0x7c, 0x93, 0x9a, 0x17, 0x5f, 0x19, 0x1c, 0x71, 0xc7, 0x2f, 0xaf, 0xac, 0x09,
	0x6f, 0x20, 0x97, 0x86, 0xb2, 0xbb, 0x6c, 0x79, 0xe9, 0x72, 0x69, 0x70, 0x06, 0x13, 0x6e, 0xbd,
	0x6c, 0x29, 0x37, 0x34, 0x18, 0x44, 0x28, 0x3a, 0xdf, 0x32, 0x9d, 0x19, 0x34, 0x8d, 0x73, 0xb8,
	0xe8, 0xbd, 0xea, 0x7b, 0x88, 0x0d, 0x15, 0xc6, 0xff, 0x3c, 0xde, 0x42, 0xd9, 0x86, 0xb5, 0x6c,
	0x99, 0x26, 0xf6, 0x65, 0xef, 0x76, 0x39, 0xb5, 0xa4, 0x0f, 0x2a, 0x87, 0x9c, 0x9d, 0x5e, 0x7c,
	0x67, 0x30, 0x3b, 0x6e, 0xa6, 0x7d, 0xe8, 0x94, 0x91, 0xe0, 0xbc, 0x65, 0x55, 0xbf, 0xe1, 0x7d,
	0xbf, 0x5f, 0x6b, 0x31, 0xa1, 0x61, 0xeb, 0x58, 0x38, 0xd3, 0xf8, 0x0c, 0xd3, 0xf8, 0xff, 0x7e,
	0xd6, 0xf8, 0x6a, 0xb5, 0xac, 0x46, 0x36, 0xa9, 0x46, 0xf6, 0x70, 0x63, 0x21, 0xab, 0x4f, 0x18,
	0xdb, 0x14, 0x6b, 0xb8, 0x3e, 0xc4, 0x78, 0xf2, 0x29, 0xf3, 0xfb, 0x13, 0xfe, 0x1c, 0x56, 0x58,
	0x97, 0xf6, 0xa8, 0x8f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x55, 0xb8, 0x46, 0xae, 0xf0, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistrationServiceClient is the client API for RegistrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistrationServiceClient interface {
	Registration(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error)
}

type registrationServiceClient struct {
	cc *grpc.ClientConn
}

func NewRegistrationServiceClient(cc *grpc.ClientConn) RegistrationServiceClient {
	return &registrationServiceClient{cc}
}

func (c *registrationServiceClient) Registration(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, "/RegistrationService.RegistrationService/Registration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationServiceServer is the server API for RegistrationService service.
type RegistrationServiceServer interface {
	Registration(context.Context, *RegistrationRequest) (*RegistrationResponse, error)
}

// UnimplementedRegistrationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRegistrationServiceServer struct {
}

func (*UnimplementedRegistrationServiceServer) Registration(ctx context.Context, req *RegistrationRequest) (*RegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registration not implemented")
}

func RegisterRegistrationServiceServer(s *grpc.Server, srv RegistrationServiceServer) {
	s.RegisterService(&_RegistrationService_serviceDesc, srv)
}

func _RegistrationService_Registration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).Registration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegistrationService.RegistrationService/Registration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).Registration(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegistrationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RegistrationService.RegistrationService",
	HandlerType: (*RegistrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Registration",
			Handler:    _RegistrationService_Registration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/Registration.proto",
}
